spring:
  application:
    name: ig-gitlab-integration
  ai:
    openai:
      base-url: https://prism-api.hinagro.com/gateway
      api-key: #Add Prism key here
gitlab:
  token: #Add your Gitlab access token
  base-url: https://emu.hinagro.com/