spring:
  application:
    name: ig-gitlab-integration
  prism:
    api:
      key: #place your prism self service key
      base:
        url:  https://prism-api.hinagro.com/gateway
  chat:
    gpt:
      model: gpt-4o
      system:
        role:system
      end:
        user:
          role: user
  ai:
    openai:
      base-url: https://prism-api.hinagro.com/gateway
      api-key: sk-IIoEWQeGHTIQcfAdcHYCmw
gitlab:
  token: glpat-oDM78m7NYqHp5fwxB5Re
  base-url: https://emu.hinagro.com/