spring:
  application:
    name: ig-gitlab-integration
  ai:
    openai:
      base-url: https://prism-api.hinagro.com/gateway
      api-key: sk-IIoEWQeGHTIQcfAdcHYCmw
gitlab:
  token: #Add Prism key here
  base-url: https://emu.hinagro.com/